services:
  - type: web
    name: fortune-ai-server
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port \
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: SERVICE_TOKEN
        sync: false
      - key: ALLOW_ORIGINS
        value: https://dnsauddmfqhsms.mycafe24.com
